# Generated by Django 4.2 on 2026-03-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamada',
            old_name='plataforma',
            new_name='setor',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='plataforma',
            new_name='setor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plataforma',
        ),
        migrations.AddField(
            model_name='user',
            name='setor',
            field=models.CharField(blank=True, help_text='Nome ou código do setor', max_length=100, null=True),
        ),
    ]
