# Generated by Django 4.2 on 2026-02-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('gestor', 'Gestor'), ('gerente', 'Gerente'), ('encarregado', 'Encarregado'), ('usuario', 'Usuário'), ('administrador', 'Administrador')], default='usuario', max_length=20),
        ),
    ]
