# Generated by Django 4.2 on 2026-03-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_rename_plataforma_chamada_setor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presenca',
            old_name='plataforma',
            new_name='setor',
        ),
    ]
